#centOS 7.x jdk8 长期支持版本
FROM 10.200.102.120/library/java8-alpine:0.0.1

#定义维护人信息
MAINTAINER jeromeLiu "jeromeliu@can-dao.com"

#复制项目代码文件
COPY ./sources/*.jar /home/trace-demo-service/sources/
COPY ./sources/lib/*.jar /home/trace-demo-service/sources/lib/
COPY ./bin/jetty.sh /home/trace-demo-service/bin/

RUN mkdir -p /data/trace-log/demo-service/ && \
	chmod 755 /data/trace-log/demo-service/ && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime

EXPOSE 6020

#CMD ["/bin/bash","-D"]
ENTRYPOINT sh /home/trace-demo-service/bin/jetty.sh start && /bin/bash
