apiVersion: v1
kind: ReplicationController
metadata:
  name: trace-demo-service
  labels:
    name: trace-demo-service
  namespace: kube-trace
spec:
  replicas: 1 #设置副本数
  selector:
    name: trace-demo-service
  template:
    metadata:
      labels:
        name: trace-demo-service
    spec:
      containers:
      - name: trace-demo-service
        image: 10.200.102.120/candao-trace/trace-demo-service:0.0.1
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - /home/trace-demo-service/bin/jetty.sh 
              - stop
        imagePullPolicy: Always
        ports:
        - containerPort: 6020
        volumeMounts:
        - mountPath: /data/trace-log/demo-service/
          name: logs
        - mountPath: /etc/localtime
          name: tz-config
        - mountPath: /home/trace-demo-service/config/
          name: properties-config
      volumes:
      - hostPath:
          path: /data/trace-log/demo-service/
        name: logs
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config
      - hostPath:
          path: /home/trace-properties/trace-demo-service/
        name: properties-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: trace-demo-service
  name: trace-demo-service
  namespace: kube-trace
spec:
  type: NodePort
  ports:
  - port: 6020
    targetPort: 6020
    #nodePort: 30620 #6020=>30620该位置的节点端口号,官方的建议是使用高位端口号,防止冲突(30000-32767)
  selector:
    name: trace-demo-service
