apiVersion: v1
kind: ReplicationController
metadata:
  name: serviceregistrycenterha2
  labels:
    name: serviceregistrycenterha2
  namespace: kube-tarce
spec:
  replicas: 1 #设置副本数
  selector:
    name: serviceregistrycenterha2
  template:
    metadata:
      labels:
        name: serviceregistrycenterha2
    spec:
      containers:
      - name: serviceregistrycenterha2
        image: 10.200.102.120/candao-tarce/tarce-service-registry-center:0.0.1
        env:
        - name: SPRING_ACTIVE
          value: serviceregistrycenterha2
        imagePullPolicy: Always
        ports:
        - containerPort: 6206
        volumeMounts:
        - mountPath: /data/tarce-log/service-registry-center/
          name: logs
        - mountPath: /etc/localtime
          name: tz-config
        - mountPath: /home/tarce-service-registry-center/config/
          name: properties-config
      volumes:
      - hostPath:
          path: /data/tarce-log/service-registry-center/
        name: logs
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config
      - hostPath:
          path: /home/tarce-properties/tarce-service-registry-center/
        name: properties-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: serviceregistrycenterha2
  name: serviceregistrycenterha2
  namespace: kube-tarce
spec:
  type: NodePort
  ports:
  - port: 6206
    targetPort: 6206
    #nodePort: 30620 #6020=>30620该位置的节点端口号,官方的建议是使用高位端口号,防止冲突(30000-32767)
  selector:
    name: serviceregistrycenterha2
  externalIPs: 
    - 10.200.102.132