apiVersion: v1
kind: ReplicationController
metadata:
  name: trace-api-gateway
  labels:
    name: trace-api-gateway
  namespace: kube-trace
spec:
  replicas: 1 #设置副本数
  selector:
    name: trace-api-gateway
  template:
    metadata:
      labels:
        name: trace-api-gateway
    spec:
      containers:
      - name: trace-api-gateway
        image: 10.200.102.120/candao-trace/trace-api-gateway:0.0.1
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - /home/trace-api-gateway/bin/jetty.sh 
              - stop
        imagePullPolicy: Always
        #resources:
          #limits:   #资源设置限制
            #cpu: "3"
            #memory: "1024Mi"
          #requests:    # (默认)硬盘：10G
            #cpu: 500m  #/单位：core数，容器启动的初始可用数量
            #memory: 200Mi  #/单位：MiB/GiB ，容器启动的初始可以数量
        ports:
        - containerPort: 4002
        volumeMounts:
        - mountPath: /data/trace-log/api-gateway/
          name: logs
        - mountPath: /etc/localtime
          name: tz-config
        - mountPath: /home/trace-api-gateway/config/
          name: properties-config
      volumes:
      - hostPath:
          path: /data/trace-log/api-gateway/
        name: logs
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config
      - hostPath:
          path: /home/trace-properties/trace-api-gateway/
        name: properties-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: trace-api-gateway
  name: trace-api-gateway
  namespace: kube-trace
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4002
    #nodePort: 30402 #4002=>30402该位置的节点端口号,官方的建议是使用高位端口号,防止冲突(30000-32767)
  selector:
    name: trace-api-gateway
  externalIPs: 
    - 10.200.102.131
