apiVersion: v1
kind: ReplicationController
metadata:
  name: trace-user-service
  labels:
    name: trace-user-service
  namespace: kube-trace
spec:
  replicas: 1 #设置副本数
  selector:
    name: trace-user-service
  template:
    metadata:
      labels:
        name: trace-user-service
    spec:
      containers:
      - name: trace-user-service
        image: 10.200.102.120/candao-trace/trace-user-service:0.0.1
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - /home/trace-user-service/bin/jetty.sh 
              - stop
        imagePullPolicy: Always
        ports:
        - containerPort: 6010
        volumeMounts: 
        - mountPath: /data/trace-log/user-service/   #挂载日志
          name: logs
        - mountPath: /etc/localtime                            #挂载宿主机时间,同步到容器
          name: tz-config
        - mountPath: /home/trace-user-service/config/
          name: properties-config
        #command:
        #["sh","/home/trace-user-service/bin/jetty_qc.sh start","/bin/bash"]
        #- sh
        #- /home/trace-user-service/startup.sh
        #- start
        #- -c
        #- /bin/bash
      volumes:
      - hostPath:
          path: /data/trace-log/user-service/
        name: logs
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: tz-config
      - hostPath:
          path: /home/trace-properties/trace-user-service/
        name: properties-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: trace-user-service
  name: trace-user-service
  namespace: kube-trace
spec:
  type: NodePort
  ports:
  - port: 6010
    targetPort: 6010
    #nodePort: 30620 #6020=>30620该位置的节点端口号,官方的建议是使用高位端口号,防止冲突(30000-32767)
  selector:
    name: trace-user-service
